# Generated by Django 2.2 on 2019-04-10 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology_used', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('image_1', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('image_2', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('image_3', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('image_4', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('image_5', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('image_6', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('project_type', models.CharField(max_length=200)),
                ('project_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
