# Generated by Django 2.2 on 2019-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190410_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_main',
            field=models.ImageField(default=0, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
